### ISSUE TITLE
Looking to help out

### ISSUE THREAD

**Issue by tindolt-zz** [Parexy/Multiplayer#10]
Hey I would like to help out can you make it so I can close issues, merge and stuff?

**Comment by tindolt-zz** [comment]
I cant push any of the updates im doing

**Comment by jacobEAdamson** [comment]
tindolt, can you make PRs for now?

**Comment by tindolt-zz** [comment]
I cant make pull requests with github desktop

**Comment by tindolt-zz** [comment]
oh wait I gotta fork it dont I
