### ISSUE TITLE
Doesn't work? 

### ISSUE THREAD

**Issue by spyrot2000** [Parexy/Multiplayer#107]
When I install this mod in my mods folder and then activate it in the correct load order, it doesn't work.

There is no "multiplayer" tab in my main menu and I can't host a server from a game either. Any help? I was using the 0.4.4 version and it worked just fine. Don't know what happend with this one.

**Comment by notfood** [comment]
For tech support go to the discord channel.

You have probably downloaded the source instead of the binary, there is no Multiplayer.dll in your Assemblies folder.
