### ISSUE TITLE
[Feature] Smart speed selection

### ISSUE THREAD

**Issue by XHawk87** [Parexy/Multiplayer#109]
Moving this in from: https://github.com/Zetrith/Multiplayer/issues/35

The basic idea is that each player has their own speed control rather than all sharing the same one. What happens right now is that if something happens and two players both press the pause button, the game will pause and then immediately unpause. It would be better if it just went at the slowest speed setting of all players. E.g. 

Player 1 is set at x3
Player 2 is paused
Player 3 is set at x1

Therefore the game is paused. However, when Player 2 unpauses and switches back to x2, the game will then go at 1x as Player 3 is now the slowest speed. 

This would have the benefit of the game never moving faster than any player wants, and if several players pause, the game remains paused until all players are ready. 

It would be nice, although not strictly necessary, to somehow display what each player's speed is set to.

**Comment by lukehedin** [comment]
Here's an alternate repo with this functionality if you or anyone else would like to play this way: https://github.com/lukehedin/Multiplayer

**Comment by XHawk87** [comment]
That's awesome. Why not create a pull request?

**Comment by notfood** [comment]
Consider making a PR to https://github.com/rwmt/Multiplayer

Because Parexy/Multiplayer is pretty much in archive mode...

**Comment by SweptWasTaken** [comment]
PR created by luke, closing this issue.
