### ISSUE TITLE
Some save files cause the host tab to not work

### ISSUE THREAD

**Issue by Parexy** [Parexy/Multiplayer#21]
I have no idea what is causing this for some people and i currently don't have one of the "corrupted" saves to test with.

**Comment by MilanDierick** [comment]
@Parexy Do you know who is experiencing this issue? Might as well ask them to send the save file.

**Comment by MilanDierick** [comment]
Closing this issue due to insufficient information.

**Comment by Parexy** [comment]
Here is a save that is causing the problem
[Notsehope.zip](https://github.com/Parexy/Multiplayer/files/3050875/Notsehope.zip)

**Comment by Pecius** [comment]
The file is corrupted, filled with 0s. We need to check the file handling (if there's any).

**Comment by Pecius** [comment]
Issue solved in #34.
