### ISSUE TITLE
Arbiter issue with CombatExtended

### ISSUE THREAD

**Issue by Dunkhan** [Parexy/Multiplayer#36]
I am working on combat extended compatibility and I have an issue where the arbiter reports a desync every time a shot is fired.

I removed all randomness and also corrected an issue I found where the CE was using sprite dimensions in code for hit calculations, but the desyncs persists. 
As far as I can determine, the shots are hitting different things on the arbiter than they are on clients. Playing with multiple clients side by side I can not observe this happening however,

It is likely another bit of code in CE causing this, but it would be great to have some help as I don't understand the details of the arbiter. Even just some documentation about how the arbiter might differ from a normal client would be helpful.

**Comment by MilanDierick** [comment]
@Dunkhan Sadly, we are still working on implementing the documentation for this mod. In the meanwhile, I can tell you that the Arbiter functions like any normal client, with the sole difference that it's the master in the whole hosting setup. It checks if the data that it has is the same on all other clients. If this is not the same, then it will throw a desync error. 

If you have any questions, feel free to ask here or on the Discord, which you can find here: https://discord.gg/W6EWU7

**Comment by MilanDierick** [comment]
Also, could you provide us with the desync files ( https://github.com/Zetrith/Multiplayer/wiki/Desyncs ) ?

**Comment by MilanDierick** [comment]
I received more information from @Parexy , and I will start implementing more extensive logging in the Arbiter, which should allow us to find out why the Arbiter is not happy with what's happening. Throwing syncing errors while there are no syncing problems is not okay.

**Comment by Dunkhan** [comment]
Sorry for not responding sooner. I didn't expect action so quickly. I certainly don't expect you to drop important things like documentation for this issue.  

I can not guarantee that there is no actual desync. I am unable to see any differences between the gamestate but I can not view every variable. Even if it is only on the arbiter it might be something like the issue I already found with the sprites, which is bad coding practice and not really the arbiter's fault. 

Should I take it that you have all you need or do you still want my desync files? It is easy enough to reproduce and I have dozens of them. I have also become quite familiar with a lot of CE code if you have questions about that.

**Comment by MilanDierick** [comment]
Please provide us with all the desync files, they will help us reproduce the desyncs that you are having.

**Comment by Dunkhan** [comment]
[Desync-215a.zip](https://github.com/Parexy/Multiplayer/files/3073250/Desync-215a.zip)

**Comment by Dunkhan** [comment]
I added some additional information to the archive. Let me know if you need anything else.

**Comment by tindolt-zz** [comment]
@Dunkhan you have tried without arbitor on I assume correct?

**Comment by Dunkhan** [comment]
Yes. I was shooting at squirrels and had a client in each monitor. I never saw the squirrel die on one and not the other which is what appeared to be happening on the arbiter. That does not mean there wasn't some other tiny difference between the clients that I didn't notice though.

**Comment by tindolt-zz** [comment]
@Dunkhan try aggresive ticking as well, its in the mod settings

**Comment by Dunkhan** [comment]
I tried aggressive ticking. Not sure what that does but I did not notice any difference.

**Comment by MilanDierick** [comment]
@Dunkhan I'm closing your issue until we have progressed a bit more in development of the mod. We are also looking to incorporate an API that will facilitate making your mod compatible with the Multiplayer mod. If you have any more information, or if you made any progress yourself, make sure to reopen this issue.
