### ISSUE TITLE
Ticks Accumulating on Lower End Machines.

### ISSUE THREAD

**Issue by SweptWasTaken** [Parexy/Multiplayer#42]
Was testing a multiplayer session the other day with a couple friends. 3 of us have pretty powerful PCs. Our 4th player however has a lower-end PC. As the game progressed, he would fall more and more behind until we had to pause. This continued for the remainder of the session. We were running no mods as I was introducing my friends to the game. I will do more testing on this in a 2 person game with my friend and update this post as needed.

I thought this might have to do with the [AMD cpu issue](https://github.com/Parexy/Multiplayer/issues/32), but he has an Intel Processor. This seems to be an issue with the way RimWorld handles FPS. This issue has also been documented here. 

https://github.com/Zetrith/Multiplayer/issues/51

**Comment by tindolt-zz** [comment]
This is tricky and we will need to change the way we handle players falling behind or the rate at which we sync ticks, as we could possibly "skip" ticks and just do it every other or every third tick as a tick is decently fast, but this could help with syncing.
