### ISSUE TITLE
Add IPv6 Support to ServerBrowser

### ISSUE THREAD

**Issue by ColinT** [Parexy/Multiplayer#55]
Although the rest of the code supports IPv6 using the IPAddress class, the ServerBrowser is unable to parse IPv6 addresses. It will throw an `MpInvalidAddress` error.

Here is the offending code:
https://github.com/Parexy/Multiplayer/blob/67ac18095445aa74fd55586d7aeb0722b2bbe626/Source/Client/Windows/ServerBrowser.cs#L516-L534

In particular the `String.split(':')` will fail to separate address and port sections due to the format of IPv6 addresses using the ':' character:

https://github.com/Parexy/Multiplayer/blob/67ac18095445aa74fd55586d7aeb0722b2bbe626/Source/Client/Windows/ServerBrowser.cs#L518

Instead, the algorithm requires a more complex regex such as `/(.*)((?::))((?:[0-9]+))$/gm`, as suggested from: https://stackoverflow.com/questions/47738068/regex-for-splitting-ipv4-and-ipv6-ipport-syntax

Demo: https://regexr.com/4cknn

**Comment by MilanDierick** [comment]
@ColinT Please make a push request and apply your suggested fix.
