### ISSUE TITLE
Desync when nps's arrive (visitors or caravan)

### ISSUE THREAD

**Issue by Wedzol** [Parexy/Multiplayer#61]
My and my friend tried everything, no mods, Core folder reinstalled, our cpu is under 90% for sure.

It happens when we start a new game, and visitor is spawning, little lag, and desync, after that nothing helps.

[Desync-09.zip](https://github.com/Parexy/Multiplayer/files/3135834/Desync-09.zip)

**Comment by Wedzol** [comment]
Thanks to Parexy, all i needed to do is enable aggressive ticking.

**Comment by Luuk-Hondius** [comment]
One of my friends also has a similar issue where he desyncs 50% of the time whenever an event spawns on our map. Some events don't cause any issues, some only a few times and others pretty much always (raids).

I (host) shared my config files and made sure he had Aggressive ticking on.
