### ISSUE TITLE
Power Switch causes out of sync

### ISSUE THREAD

**Issue by senioi** [Parexy/Multiplayer#68]
Clicking "on" or "off"

**Comment by MilanDierick** [comment]
@senioi I just tested your issue by switching a power switch, and it didn't desync for me. Please provide me with the following: 
- All of your desync files (https://github.com/Parexy/Multiplayer/wiki/Desyncs)
- Steps to reproduce your problem
- Are any of the players using an AMD processor?
- What type of connection is being used (Direct, LAN, Steam)?

**Comment by senioi** [comment]
@MilanDierick  Thanks for your reply
1. this is Desyncs [Desync-79.zip](https://github.com/Parexy/Multiplayer/files/3178425/Desync-79.zip)
2.I have enable RT_PowerSwitch
[RT_PowerSwitch-1.0-1.0.13.zip](https://github.com/Parexy/Multiplayer/files/3178436/RT_PowerSwitch-1.0-1.0.13.zip)
 ,this switch "on" or "off" 100% client desync/
3. all is intel CPU
4.LAN

**Comment by MilanDierick** [comment]
@senioi Using the RT Power Switch mod is not supported, as it adds new UI features. Until the mod owner makes his mod compatible with the Multiplayer mod, you won't be able to use the mod in your play through.
