### ISSUE TITLE
Document code contribution process

### ISSUE THREAD

**Issue by jacobEAdamson** [Parexy/Multiplayer#9]
Document how a user should take an issue, build the project, and push the code back so that new contributors can easily get started.

**Comment by tindolt-zz** [comment]
@Parexy should do this

**Comment by jacobEAdamson** [comment]
[Related branch](https://github.com/Parexy/Multiplayer/tree/issue-9)

**Comment by MilanDierick** [comment]
This document now states that push requests should be made to the development branch instead of the master branch.
