### ISSUE TITLE
Proposal: Precomputed Direct IPs for hosting

### ISSUE THREAD

**Issue by vasilevp** [Parexy/Multiplayer#92]
Letting the user enter an arbitrary IP for hosting is often confusing and error-prone: for example, an inexperienced user might decide to enter their external IP when they're behind a NAT.
I suggest we detect all IPs currently available to the OS and present the user with a more limited choice.

I currently have a working prototype (needs some GUI adjustments though):
![image](https://user-images.githubusercontent.com/1939685/60311749-4e892900-9961-11e9-8e62-4ff6edd34594.png)

If that's something worth adding, I could drop a PR this weekend, together with full IPv6 support.

**Comment by notfood** [comment]
I think it's just best to listen to any always. There is very few reasons to not do that.

**Comment by vasilevp** [comment]
Fair enough.
