### ISSUE TITLE
Precompiled 0MultiplayerAPI.dll should be downloadable

### ISSUE THREAD

**Issue by pardeike** [Parexy/Multiplayer#95]
Make it available from Mod Support via a link or make it a separate (sub)repo with its own releases. Ultimately, I want this to be a nuget release just like Harmony.

**Comment by notfood** [comment]
I hope this works!

https://www.nuget.org/packages/RimWorld.MultiplayerAPI/

Parexy is away so we can't release anything on github in the meantime.

**Comment by pardeike** [comment]
Excellent! Now make sure this is documented and then close this issue.

**Comment by SweptWasTaken** [comment]
Documented [here](https://hackmd.io/Gd_gueokTNui_fqzOSG2Tg?view#API)
