### ISSUE TITLE
Caravan Gifts to Hostile Factions broken

### ISSUE THREAD

**Issue by blubbi321** [Parexy/Multiplayer#99]
When delivering gifts via caravans to hostile factions the trading menu just briefly opens and then immediately closes right after so that a trade/gift cannot be made. The issue is resolved when all other players leave the session.

This https://github.com/Parexy/Multiplayer/issues/1 looks related (so just mark this as duplicate in case all caravan related things are turned off).

**Comment by notfood** [comment]
Fixed by https://github.com/Parexy/Multiplayer/commit/5cc688caa70527aba66417b4f5d4acf3e7f73792

Use steam version or wait for 0.4.8.3
